# Generated by Django 5.2.15 on 2026-06-19 12:43

import django.db.models.deletion
import eventyay.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0030_room_is_unscheduled_team_polls_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="SusiConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        help_text="Base URL of the SUSI Translator Flask server, e.g. https://susi.example.com",
                        verbose_name="SUSI server URL",
                    ),
                ),
                (
                    "auth_token",
                    models.TextField(
                        blank=True,
                        help_text="JWT or long-lived token used to authenticate against the SUSI server. Sent as a Bearer token; never exposed to attendees.",
                        verbose_name="Authentication token",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch for SUSI interpretation on this event.",
                        verbose_name="Enable interpretation",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="susi_connection",
                        to="base.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "SUSI connection",
                "verbose_name_plural": "SUSI connections",
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name="RoomInterpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hls_url",
                    models.URLField(
                        blank=True,
                        help_text="HLS (.m3u8) URL of the room's audio/video stream that SUSI will ingest. Defaults from the room's stream configuration when empty.",
                        verbose_name="HLS stream URL",
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        blank=True,
                        help_text="Spoken language of the stream, e.g. 'en'.",
                        max_length=20,
                        verbose_name="Source language",
                    ),
                ),
                (
                    "target_languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Languages to translate into, e.g. ['de', 'fr'].",
                        verbose_name="Target languages",
                    ),
                ),
                (
                    "transcription_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Transcription provider"
                    ),
                ),
                (
                    "translation_provider",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Translation provider"
                    ),
                ),
                (
                    "susi_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Tenant ID returned by SUSI when the session starts.",
                        max_length=64,
                        verbose_name="SUSI session/tenant ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretation",
                        to="base.room",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="interpretation.susiconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room interpretation",
                "verbose_name_plural": "Room interpretations",
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
    ]
