# Generated by Django 6.0.7 on 2026-08-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0012_voxbentooauthgrant_webhook_scope_denied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='event_provisioning_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='room_sync_failed',
            field=models.BooleanField(default=False),
        ),
    ]
