# Generated by Django 6.0.7 on 2026-08-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0013_voxbentooauthgrant_event_provisioning_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='event_provisioned',
            field=models.BooleanField(default=False),
        ),
    ]
