# Generated by Django 6.0.7 on 2026-08-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interpretation', '0014_voxbentooauthgrant_event_provisioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxbentooauthgrant',
            name='is_disconnected',
            field=models.BooleanField(default=False),
        ),
    ]
